// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    CardAuth: typeof import('./src/components/CardAuth.vue')['default']
    DeviceStatus: typeof import('./src/components/DeviceStatus.vue')['default']
    PasswordAuth: typeof import('./src/components/PasswordAuth.vue')['default']
    TheLogin: typeof import('./src/components/TheLogin.vue')['default']
    TheMain: typeof import('./src/components/TheMain.vue')['default']
  }
}
